### ISSUE TITLE
你好啊，请问如何添加词典，部署后里面词典是空的，一个词典也没有。

### ISSUE THREAD

**Issue by zgpnuaa** [jiangnianshun/django-mdict#1]
![image](https://user-images.githubusercontent.com/38033949/142872198-d428bca4-46c8-49b4-a3e1-7d26566f8595.png)

**Comment by jiangnianshun** [comment]
你好，启动时命令行显示信息可以截图吗。我猜可能的原因：
1.可能时路径没有设置好，命令行中[INIT_UTILS.INIT_MDICT_LIST] media root path后显示的是当前选择的目录，运行init_mdict_path.py可以重新选择路径。
2可能是mdx没有被识别，原因可能是
2.1词典是lzo压缩的，没有安装python-lzo
2.2词典是mdxbuilder4.0制作的。

**Comment by zgpnuaa** [comment]
![image](https://user-images.githubusercontent.com/38033949/142883258-9347d60c-23bf-44d0-9826-d29eecf700f6.png)
启动时命令行显示信息显示：
[INIT_UTILS.INIT_MDICT_LIST] media root path: /home/zhugaoping/VSCodeWorkspace/django-mdict/media/mdict/doc
[INIT_UTILS.CHECK_DIR_CHANGE] mdict_root_path not exists.
[INIT_UTILS.INIT_MDICT_LIST] [0.0436s] initializing mdict_list
[INIT_UTILS.INIT_MDICT_LIST] [0.0004s] creating cache file
[INIT_UTILS.INIT_MDICT_LIST] dictionary counts 0
[INIT_UTILS.INIT_MDICT_LIST] [0.0441s] initializing

**Comment by jiangnianshun** [comment]
从图上看没啥问题，在指定的路径下没有搜索到mdx，所以回到了默认django-mdict/media/doc路径，尝试直接修改mdict_path.json，确认路径正确还不行的话，说明代码哪里有问题吧，我这里没有复现问题，暂时没法修改。

**Comment by zgpnuaa** [comment]
哦哦，我搜了整个文件夹也没找到mdx文件，这个文件mdx是要自己去网上下载吗？还是程序自己生成啊？在你的github仓库里也没找到这个格式的文件。我是在ubuntu部署的，可能运行流程没整对吧。

**Comment by jiangnianshun** [comment]
是的，需要自己下载或自己制作。
目前只支持mdx和zim格式。
mdx,mdd是mdict格式的词典，可以去pdawiki和freemdict获取资源。
zim是离线维基百科，可以去wiki页面下载。
正式的mdx词典软件有mdict,goldendict,欧陆等等。

**Comment by zgpnuaa** [comment]
在网上下载了几本词典OK了，但是不能发音，要是能像有道谷歌一样还能翻译句子和段落就好了😁

**Comment by jiangnianshun** [comment]
发音是词典自带的，或者下载单独的发音库（只有mdd）文件，并设置audio_path。
翻译功能没有。其他词典软件欧陆是有翻译功能的，goldendict也可以通过插件实现，还有一些也有。

**Comment by zgpnuaa** [comment]
好的，我了解了，谢谢，你这个也很棒了。
