### ISSUE TITLE
点击全文检索出现下面的错误

### ISSUE THREAD

**Issue by Jiangws2002** [jiangnianshun/django-mdict#2]
词典很好用！谢谢。

![image](https://user-images.githubusercontent.com/93924709/146597130-3181836e-1016-4a87-9004-aad619ef2cb4.png)

ConnectionError(<urllib3.connection.HTTPConnection object at 0x00000207D4B66E08>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x00000207D4B66E08>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it)
[18/Dec/2021 03:26:18] "GET /mdict/indexstatus/ HTTP/1.1" 200 191
<urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>
[18/Dec/2021 03:26:19] "GET /mdict/deckgroup/ HTTP/1.1" 200 7

**Comment by jiangnianshun** [comment]
与es连接失败，1.检查是否开启了es，2.检查es端口是否正确设置。
mdx的全文搜索是用外置es实现的，很简单，很粗糙，gd等软件有内置全文搜索功能，那个会更方便一些。

**Comment by Jiangws2002** [comment]
> 与es连接失败，1.检查是否开启了es，2.检查es端口是否正确设置。 mdx的全文搜索是用外置es实现的，很简单，很粗糙，gd等软件有内置全文搜索功能，那个会更方便一些。

谢谢回音，我会检查下es. GD的全文检索很慢，想试试你这个。

**Comment by jiangnianshun** [comment]
django-mdict/config.ini设置
```
es_host = http://127.0.0.1:9200/
```
elasticsearch-7.10.1/config/elasticsearch.yml设置
```
http.port: 9200
```
es占用资源太大，我分了6g内存还不能囊括所有词典，还是推荐能用正规软件解决的用正规软件。

**Comment by Jiangws2002** [comment]
Hi Mr. Jiang,

我试了下，还是不行，没有关系，不全文检索也无所谓。

我觉得你这个词典已经写得很好了，我也很想参与，不知道有什么我帮得上忙的。我对Python
和Django也是看到你这个项目才开始学习的，但我程序经验有的。

我也姓江。
谢谢你。

**Comment by jiangnianshun** [comment]
可能没过防火墙？
我不是程序员，这就是个脚本，随便改，可以pull request。
对于我来说一个是满足自己的一些需求，再一个就是对python的学习，这个就是边学边做的脚本，随便改。

**Comment by Jiangws2002** [comment]
Hi Mr. Jiang,

我已经成功设置好了，原来ES还要在词典那边启动一下，谢谢你。
全文还是很快的，谢谢你。
