### ISSUE TITLE
关于锚点跳转

### ISSUE THREAD

**Issue by Jiangws2002** [jiangnianshun/django-mdict#3]
HI jiangnianshun, 你好。

比如我设置<a href="entry://目标词条#目标ID">链接内容</a>，跳到另一个词的<a id="目标ID"></a>的地方。
试了下，好像不支持。能修改成支持的吗？谢谢。

细节请见：
[https://www.pdawiki.com/forum/forum.php?mod=viewthread&tid=39790&highlight=%E8%B7%B3%E8%BD%AC](https://www.pdawiki.com/forum/forum.php?mod=viewthread&tid=39790&highlight=%E8%B7%B3%E8%BD%AC)

**Comment by jiangnianshun** [comment]
好的，感谢反馈。这里好像是iframe有啥问题来着，我会再检查检查，大概得周末。

**Comment by Jiangws2002** [comment]
> 

麻烦你了。

**Comment by jiangnianshun** [comment]
进行部分修复。跳转新词条后，只有位于第一位置的词条会自动打开，然后自动跳转锚点。

**Comment by Jiangws2002** [comment]
谢谢你的修改，已经很实用了。
